csk/urls.py
from django.urls import path
from csk.views import *

app_name='csk'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni')
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb


urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *

app_name='rcb'
urlpatterns=[
    path('virat/',virat,name='virat')
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here
def dhoni(request):
    return render(request,'dhoni.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=?, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>hiii</h1>
       <h1></h1> <a href="{% url 'rcb:virat' %}">link</a></h1>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=?, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hiii</h1>
            <h1><a href="{% url 'csk:dhoni' %}">link</a>
            </h1></center>
</body>
</html>